
import java.awt.BorderLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author María Cospin
 */
public class RegistrarNuevoProducto extends javax.swing.JPanel {
    Velas nuevo;
    ArrayList<Velas> velas;

    /**
     * Creates new form RegistrarNuevoProducto
     */
    public RegistrarNuevoProducto() {
        initComponents();
        bMostrar.setVisible(false);
        velas = new ArrayList();
    }
    
    public String getSelectedCat() {
        return selectedCat;
    }
    
    private String selectedCat;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Hoja2 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        GuardarPuertas = new javax.swing.JButton();
        IngresarNumeroPuertas = new javax.swing.JLabel();
        ExistenciasRespuesta = new javax.swing.JTextField();
        IngresarVelocidad = new javax.swing.JLabel();
        NumeroVelaRespuesta = new javax.swing.JTextField();
        IngresarMarca = new javax.swing.JLabel();
        PrecioRespuesta = new javax.swing.JTextField();
        IngresarModelo = new javax.swing.JLabel();
        IngresarAñoFabricacion = new javax.swing.JLabel();
        MateriaPrimaUsadaRespuesta = new javax.swing.JTextField();
        IngresarMarca1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ComboBxTemporada = new javax.swing.JComboBox<>();
        ComboBxCategoria = new javax.swing.JComboBox<>();
        RegresarAMenu = new javax.swing.JButton();
        bMostrar = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(872, 483));

        Hoja2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("ARTÍCULOS");

        jLabel8.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Totus Tuus");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                        .addGap(22, 22, 22)))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(255, 233, 133));
        jPanel5.setForeground(new java.awt.Color(255, 228, 146));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(255, 233, 133));
        jPanel3.setForeground(new java.awt.Color(255, 228, 146));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(255, 233, 133));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(255, 233, 133));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 22, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        GuardarPuertas.setText("Guardar");
        GuardarPuertas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarPuertasActionPerformed(evt);
            }
        });

        IngresarNumeroPuertas.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        IngresarNumeroPuertas.setText("Cantidad en existencias");
        IngresarNumeroPuertas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        IngresarNumeroPuertas.setVerifyInputWhenFocusTarget(false);

        IngresarVelocidad.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        IngresarVelocidad.setText("No. Vela");
        IngresarVelocidad.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        IngresarVelocidad.setVerifyInputWhenFocusTarget(false);

        NumeroVelaRespuesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumeroVelaRespuestaActionPerformed(evt);
            }
        });

        IngresarMarca.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        IngresarMarca.setText("Precio");
        IngresarMarca.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        IngresarMarca.setVerifyInputWhenFocusTarget(false);

        IngresarModelo.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        IngresarModelo.setText("Temporada");
        IngresarModelo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        IngresarModelo.setVerifyInputWhenFocusTarget(false);

        IngresarAñoFabricacion.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        IngresarAñoFabricacion.setText("Laminas de materia prima  usada");
        IngresarAñoFabricacion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        IngresarAñoFabricacion.setVerifyInputWhenFocusTarget(false);

        IngresarMarca1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        IngresarMarca1.setText("Categoria");
        IngresarMarca1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        IngresarMarca1.setVerifyInputWhenFocusTarget(false);

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 36)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Registrar nuevo producto");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        ComboBxTemporada.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Navideña", "Día de la madre", "Religiosa", "Personalizada" }));

        ComboBxCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Entorchada", "Cilindrica", "Corazón", "Formas varias" }));

        RegresarAMenu.setText("Regresar a menú");
        RegresarAMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarAMenuActionPerformed(evt);
            }
        });

        bMostrar.setText("Mostrar");
        bMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMostrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Hoja2Layout = new javax.swing.GroupLayout(Hoja2);
        Hoja2.setLayout(Hoja2Layout);
        Hoja2Layout.setHorizontalGroup(
            Hoja2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Hoja2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(Hoja2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Hoja2Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addGroup(Hoja2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Hoja2Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(Hoja2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(IngresarVelocidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(NumeroVelaRespuesta)
                                    .addComponent(IngresarMarca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(PrecioRespuesta)
                                    .addComponent(IngresarMarca1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ComboBxCategoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(93, 93, 93)
                                .addGroup(Hoja2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(Hoja2Layout.createSequentialGroup()
                                        .addComponent(MateriaPrimaUsadaRespuesta)
                                        .addGap(79, 79, 79))
                                    .addComponent(IngresarAñoFabricacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(Hoja2Layout.createSequentialGroup()
                                        .addComponent(IngresarNumeroPuertas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(1, 1, 1))
                                    .addGroup(Hoja2Layout.createSequentialGroup()
                                        .addComponent(ExistenciasRespuesta)
                                        .addGap(79, 79, 79))
                                    .addGroup(Hoja2Layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addGroup(Hoja2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(IngresarModelo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(ComboBxTemporada, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(78, 78, 78))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Hoja2Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(21, 21, 21)))
                        .addGap(87, 87, 87))
                    .addGroup(Hoja2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(578, 578, 578))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Hoja2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(RegresarAMenu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(Hoja2Layout.createSequentialGroup()
                        .addGap(306, 306, 306)
                        .addGroup(Hoja2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(GuardarPuertas, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                            .addComponent(bMostrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        Hoja2Layout.setVerticalGroup(
            Hoja2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Hoja2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(28, 28, 28)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                .addGap(26, 26, 26)
                .addGroup(Hoja2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Hoja2Layout.createSequentialGroup()
                        .addComponent(IngresarVelocidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NumeroVelaRespuesta)
                        .addGap(23, 23, 23)
                        .addComponent(IngresarMarca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PrecioRespuesta)
                        .addGap(23, 23, 23)
                        .addComponent(IngresarMarca1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ComboBxCategoria))
                    .addGroup(Hoja2Layout.createSequentialGroup()
                        .addComponent(IngresarModelo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ComboBxTemporada)
                        .addGap(23, 23, 23)
                        .addComponent(IngresarAñoFabricacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MateriaPrimaUsadaRespuesta)
                        .addGap(23, 23, 23)
                        .addComponent(IngresarNumeroPuertas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ExistenciasRespuesta)))
                .addGap(9, 9, 9)
                .addComponent(GuardarPuertas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bMostrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RegresarAMenu)
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Hoja2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Hoja2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void GuardarPuertasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarPuertasActionPerformed
        // TODO add your handling code here:
        try{
            int NumeroVela = Integer.parseInt(NumeroVelaRespuesta.getText());
            double Precio = Double.parseDouble(PrecioRespuesta.getText());
            int Existencias = Integer.parseInt(ExistenciasRespuesta.getText());
            double MateriaPrimaUsada  = Double.parseDouble(MateriaPrimaUsadaRespuesta.getText());
            nuevo = new Velas();
            nuevo.setNumeroVela(NumeroVela);
            nuevo.setPrecio(Precio);
            nuevo.setExistencias(Existencias);
            nuevo.setCantidadLaminaUsada(MateriaPrimaUsada);
            
            int comboBoxTemp = ComboBxTemporada.getSelectedIndex();
            String selectedTemporada = (String) ComboBxTemporada.getSelectedItem();

            if (comboBoxTemp == 0) {
                nuevo.setTemporada(selectedTemporada);
            } else if (comboBoxTemp == 1) {
                nuevo.setTemporada(selectedTemporada);
            } else if (comboBoxTemp == 2) {
                nuevo.setTemporada(selectedTemporada);
            }
            
            int comboBoxCat = ComboBxCategoria.getSelectedIndex();
            selectedCat = (String) ComboBxCategoria.getSelectedItem();
            
            if (comboBoxCat == 0){
                nuevo.setCategoría(selectedCat);
            } else if (comboBoxTemp == 1) {
                nuevo.setCategoría(selectedCat);
            } else if (comboBoxTemp == 2) {
                nuevo.setCategoría(selectedCat);
            }
            
            JOptionPane.showMessageDialog(null, "Información guardada correctamente");
            bMostrar.setVisible(true);
            
            velas.add(nuevo);
        }

        catch (NumberFormatException ex){
            JOptionPane.showMessageDialog(null, "Verifique que los datos ingresados sean correctos / Verifique que todos los campos hallan sido respondidos",
                    "Error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_GuardarPuertasActionPerformed

    private void NumeroVelaRespuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumeroVelaRespuestaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumeroVelaRespuestaActionPerformed

    private void RegresarAMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarAMenuActionPerformed
        // TODO add your handling code here:
        PanelMenu menu = new PanelMenu();
        menu.setSize (868,483);
        menu.setLocation (0,0);
        
        Hoja2.removeAll();
        Hoja2.add(menu,BorderLayout.CENTER);
        Hoja2.revalidate();
        Hoja2.repaint();
    }//GEN-LAST:event_RegresarAMenuActionPerformed

    private void bMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMostrarActionPerformed
        // TODO add your handling code here:
       for(int i=0; i<velas.size(); i++){
        JOptionPane.showMessageDialog(null, "No. Vela: " + velas.get(i).getNumeroVela() + "\n"+ "Categoría: " + velas.get(i).getCategoría() + "\n"+ 
                "Temporada: " + velas.get(i).getTemporada() + "\n"+ "Materia Prima Usada: " + velas.get(i).getCantidadLaminaUsada() + " Lamina/as usada/as" + "\n"+ "Existencias: " + velas.get(i).getExistencias() + "\n"+ "Precio: Q" + velas.get(i).getPrecio() );
        }
    }//GEN-LAST:event_bMostrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBxCategoria;
    private javax.swing.JComboBox<String> ComboBxTemporada;
    private javax.swing.JTextField ExistenciasRespuesta;
    private javax.swing.JButton GuardarPuertas;
    private javax.swing.JPanel Hoja2;
    private javax.swing.JLabel IngresarAñoFabricacion;
    private javax.swing.JLabel IngresarMarca;
    private javax.swing.JLabel IngresarMarca1;
    private javax.swing.JLabel IngresarModelo;
    private javax.swing.JLabel IngresarNumeroPuertas;
    private javax.swing.JLabel IngresarVelocidad;
    private javax.swing.JTextField MateriaPrimaUsadaRespuesta;
    private javax.swing.JTextField NumeroVelaRespuesta;
    private javax.swing.JTextField PrecioRespuesta;
    private javax.swing.JButton RegresarAMenu;
    private javax.swing.JButton bMostrar;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables
}
